[package]
name = "pico_rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-stream = "0.3"
async-trait = "0.1"
futures = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "macros"] }
tracing = { workspace = true }
nimiq-jsonrpc-client = { git = "https://github.com/cadenkriese/jsonrpc.git", rev = "43a358090f23f411a6eb4a126d12cdae588c6de3" }
nimiq-jsonrpc-core = { git = "https://github.com/cadenkriese/jsonrpc.git", rev = "43a358090f23f411a6eb4a126d12cdae588c6de3" }
